#!/bin/bash
cd ../..
mkdir data/stash
cd data/stash
git clone ssh://git@stash:7999/lib/alert-log-domain.git
git clone ssh://git@stash:7999/lib/amqp-configuration-domain.git
git clone ssh://git@stash:7999/lib/answer-delivery-domain.git
git clone ssh://git@stash:7999/lib/auction-partner-internal.git
git clone ssh://git@stash:7999/lib/bbg-domain.git
git clone ssh://git@stash:7999/lib/bmc-impact-service.git
git clone ssh://git@stash:7999/lib/build-levels.git
git clone ssh://git@stash:7999/lib/captcha-extensions.git
git clone ssh://git@stash:7999/lib/captcha-struts1-extensions.git
git clone ssh://git@stash:7999/lib/carfax-annotations.git
git clone ssh://git@stash:7999/lib/carfax-assertions.git
git clone ssh://git@stash:7999/lib/carfax-auction-bridge.git
git clone ssh://git@stash:7999/lib/carfax-autoreports-summary.git
git clone ssh://git@stash:7999/lib/carfax-autoreports-summary-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-branding-domain.git
git clone ssh://git@stash:7999/lib/carfax-commons-controlm.git
git clone ssh://git@stash:7999/lib/carfax-connection-cache.git
git clone ssh://git@stash:7999/lib/carfax-connection-manager.git
git clone ssh://git@stash:7999/lib/carfax-core-consumer.git
git clone ssh://git@stash:7999/lib/carfax-core-partner.git
git clone ssh://git@stash:7999/lib/carfax-core-subscriber.git
git clone ssh://git@stash:7999/lib/carfax-core-subscriber-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-core-usage.git
git clone ssh://git@stash:7999/lib/carfax-core-usage-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-core-utilities.git
git clone ssh://git@stash:7999/lib/carfax-core-vhr.git
git clone ssh://git@stash:7999/lib/carfax-core-vindecode.git
git clone ssh://git@stash:7999/lib/carfax-cvs-navigator.git
git clone ssh://git@stash:7999/lib/carfax-datetime-framework.git
git clone ssh://git@stash:7999/lib/carfax-db-utils.git
git clone ssh://git@stash:7999/lib/carfax-deeplinks.git
git clone ssh://git@stash:7999/lib/carfax-deeplinks-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-email-commons.git
git clone ssh://git@stash:7999/lib/carfax-fitnesse-commons.git
git clone ssh://git@stash:7999/lib/carfax-integrator-files.git
git clone ssh://git@stash:7999/lib/carfax-integrator-files-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-language-tools.git
git clone ssh://git@stash:7999/lib/carfax-logging-commons.git
git clone ssh://git@stash:7999/lib/carfax-messaging-commons.git
git clone ssh://git@stash:7999/lib/carfax-oncontact-testing.git
git clone ssh://git@stash:7999/lib/carfax-partner.git
git clone ssh://git@stash:7999/lib/carfax-product-commons.git
git clone ssh://git@stash:7999/lib/carfax-product-consumer-ratings.git
git clone ssh://git@stash:7999/lib/carfax-product-glossary.git
git clone ssh://git@stash:7999/lib/carfax-product-hotlistings.git
git clone ssh://git@stash:7999/lib/carfax-product-hotlistings-acceptance.git
git clone ssh://git@stash:7999/lib/carfax-product-testing.git
git clone ssh://git@stash:7999/lib/carfax-purchase-internal.git
git clone ssh://git@stash:7999/lib/carfax-shared.git
git clone ssh://git@stash:7999/lib/carfax-snmp.git
git clone ssh://git@stash:7999/lib/carfax-spring-datasources.git
git clone ssh://git@stash:7999/lib/carfax-sql-framework.git
git clone ssh://git@stash:7999/lib/carfax-struts-validator.git
git clone ssh://git@stash:7999/lib/carfax-struts2-extensions.git
git clone ssh://git@stash:7999/lib/carfax-testing.git
git clone ssh://git@stash:7999/lib/carfax-web-dbaccess.git
git clone ssh://git@stash:7999/lib/carfax-websidestory.git
git clone ssh://git@stash:7999/lib/carfax-xinfo.git
git clone ssh://git@stash:7999/lib/carfaxonline-auction-internal.git
git clone ssh://git@stash:7999/lib/carfaxonline-encryption.git
git clone ssh://git@stash:7999/lib/carfaxonline-java.git
git clone ssh://git@stash:7999/lib/carfaxonline-java-acceptance.git
git clone ssh://git@stash:7999/lib/certification-management-domain.git
git clone ssh://git@stash:7999/lib/click-tracking-domain.git
git clone ssh://git@stash:7999/lib/coffeescript-extensions.git
git clone ssh://git@stash:7999/lib/coldfusionerrorhandler-domain.git
git clone ssh://git@stash:7999/lib/configuration-domain.git
git clone ssh://git@stash:7999/lib/configuration-extensions.git
git clone ssh://git@stash:7999/lib/consignor-alert-domain.git
git clone ssh://git@stash:7999/lib/consumer-account-domain.git
git clone ssh://git@stash:7999/lib/consumer-email-domain.git
git clone ssh://git@stash:7999/lib/consumer-fitnesse.git
git clone ssh://git@stash:7999/lib/consumer-partner-domain.git
git clone ssh://git@stash:7999/lib/consumer-startup-domain.git
git clone ssh://git@stash:7999/lib/consumer-tags.git
git clone ssh://git@stash:7999/lib/consumer-testing-internal.git
git clone ssh://git@stash:7999/lib/controlm-web-service-client.git
git clone ssh://git@stash:7999/lib/copernicus-domain.git
git clone ssh://git@stash:7999/lib/copernicus-internal.git
git clone ssh://git@stash:7999/lib/CoreVip.git
git clone ssh://git@stash:7999/lib/corevip-acceptance.git
git clone ssh://git@stash:7999/lib/creditcard-domain.git
git clone ssh://git@stash:7999/lib/cvs-repository-plugin.git
git clone ssh://git@stash:7999/lib/dartads-domain.git
git clone ssh://git@stash:7999/lib/datasource-provider-domain.git
git clone ssh://git@stash:7999/lib/date-time-domain.git
git clone ssh://git@stash:7999/lib/dealer-internal.git
git clone ssh://git@stash:7999/lib/dealer-inventory-domain.git
git clone ssh://git@stash:7999/lib/dealer-inventory-domain-acceptance.git
git clone ssh://git@stash:7999/lib/dealer-user-domain.git
git clone ssh://git@stash:7999/lib/dealer-user-domain-acceptance.git
git clone ssh://git@stash:7999/lib/dealerautoreports-commons.git
git clone ssh://git@stash:7999/lib/dealerautoreports-commons-acceptance.git
git clone ssh://git@stash:7999/lib/dealerautoreports-dataqualityengine.git
git clone ssh://git@stash:7999/lib/DealerAutoReports-DataQualityEngine-acceptance.git
git clone ssh://git@stash:7999/lib/dealerpartnerfitnesse.git
git clone ssh://git@stash:7999/lib/deploy-gradle-plugins.git
git clone ssh://git@stash:7999/lib/dris-xml.git
git clone ssh://git@stash:7999/lib/encryption-extensions.git
git clone ssh://git@stash:7999/lib/file-repository-plugin.git
git clone ssh://git@stash:7999/lib/fitnesse-extensions.git
git clone ssh://git@stash:7999/lib/fitnesse-wiki-widgets.git
git clone ssh://git@stash:7999/lib/fordlincoln-lookback-domain.git
git clone ssh://git@stash:7999/lib/ftp-repository-plugin.git
git clone ssh://git@stash:7999/lib/git-repository-plugin.git
git clone ssh://git@stash:7999/lib/gradle-plugins.git
git clone ssh://git@stash:7999/lib/grails-logging-defaults.git
git clone ssh://git@stash:7999/lib/gson-extensions.git
git clone ssh://git@stash:7999/lib/harness.git
git clone ssh://git@stash:7999/lib/hotlisting-connection-manager.git
git clone ssh://git@stash:7999/lib/hudson-monitor.git
git clone ssh://git@stash:7999/lib/in-memory-database.git
git clone ssh://git@stash:7999/lib/jaguar-common.git
git clone ssh://git@stash:7999/lib/jasmine-extensions.git
git clone ssh://git@stash:7999/lib/jetty-extensions.git
git clone ssh://git@stash:7999/lib/jspec-assertions.git
git clone ssh://git@stash:7999/lib/jsspec-runner.git
git clone ssh://git@stash:7999/lib/junit-extensions.git
git clone ssh://git@stash:7999/lib/kount-domain.git
git clone ssh://git@stash:7999/lib/location-domain.git
git clone ssh://git@stash:7999/lib/logging-extensions.git
git clone ssh://git@stash:7999/lib/lucene-extensions.git
git clone ssh://git@stash:7999/lib/magrathea-database-domain.git
git clone ssh://git@stash:7999/lib/magrathea-domain.git
git clone ssh://git@stash:7999/lib/magrathea-internal.git
git clone ssh://git@stash:7999/lib/message-domain.git
git clone ssh://git@stash:7999/lib/messaging-adapters.git
git clone ssh://git@stash:7999/lib/mrv-analysis-domain.git
git clone ssh://git@stash:7999/lib/name-in-lights.git
git clone ssh://git@stash:7999/lib/name-in-lights-acceptance.git
git clone ssh://git@stash:7999/lib/nmvtis-domain.git
git clone ssh://git@stash:7999/lib/one-account-domain.git
git clone ssh://git@stash:7999/lib/oracle-connection-manager.git
git clone ssh://git@stash:7999/lib/oracle-repository-plugin.git
git clone ssh://git@stash:7999/lib/partner-domain.git
git clone ssh://git@stash:7999/lib/partner-encryption.git
git clone ssh://git@stash:7999/lib/phoenix-permutation.git
git clone ssh://git@stash:7999/lib/pool-member-domain.git
git clone ssh://git@stash:7999/lib/postal-domain.git
git clone ssh://git@stash:7999/lib/ProgressMonitoring.git
git clone ssh://git@stash:7999/lib/project-build-results.git
git clone ssh://git@stash:7999/lib/purchase-domain.git
git clone ssh://git@stash:7999/lib/purchase-testing-internal.git
git clone ssh://git@stash:7999/lib/quick-vin-plate-match-internal.git
git clone ssh://git@stash:7999/lib/quickvin-client.git
git clone ssh://git@stash:7999/lib/quickvin-domain.git
git clone ssh://git@stash:7999/lib/rabbit-extensions.git
git clone ssh://git@stash:7999/lib/rbs-domain.git
git clone ssh://git@stash:7999/lib/recordcheck-domain.git
git clone ssh://git@stash:7999/lib/reflection-extensions.git
git clone ssh://git@stash:7999/lib/report-delivery-domain.git
git clone ssh://git@stash:7999/lib/repository-plugin-domain.git
git clone ssh://git@stash:7999/lib/rest-client.git
git clone ssh://git@stash:7999/lib/rest-client-extensions.git
git clone ssh://git@stash:7999/lib/serialization-extensions.git
git clone ssh://git@stash:7999/lib/service-history-check-domain.git
git clone ssh://git@stash:7999/lib/servlet-extensions.git
git clone ssh://git@stash:7999/lib/silverpop-api.git
git clone ssh://git@stash:7999/lib/snapshot-domain.git
git clone ssh://git@stash:7999/lib/socket-java.git
git clone ssh://git@stash:7999/lib/spring-amqp-extras.git
git clone ssh://git@stash:7999/lib/spring-email-extentions.git
git clone ssh://git@stash:7999/lib/spring-extensions.git
git clone ssh://git@stash:7999/lib/spring-flash-map.git
git clone ssh://git@stash:7999/lib/sql-extensions.git
git clone ssh://git@stash:7999/lib/sql-framework-extensions.git
git clone ssh://git@stash:7999/lib/status-page-domain.git
git clone ssh://git@stash:7999/lib/struts1-extensions.git
git clone ssh://git@stash:7999/lib/subscriber-domain.git
git clone ssh://git@stash:7999/lib/survey.git
git clone ssh://git@stash:7999/lib/survey-acceptance.git
git clone ssh://git@stash:7999/lib/test-helpers.git
git clone ssh://git@stash:7999/lib/test-user-credentials-domain.git
git clone ssh://git@stash:7999/lib/testhelpers.git
git clone ssh://git@stash:7999/lib/ThreadedBatchManager.git
git clone ssh://git@stash:7999/lib/timing-utils-extensions.git
git clone ssh://git@stash:7999/lib/UdpLogging.git
git clone ssh://git@stash:7999/lib/user-abstraction-layer-extensions.git
git clone ssh://git@stash:7999/lib/vhdata-cache-client.git
git clone ssh://git@stash:7999/lib/vhdb-commons.git
git clone ssh://git@stash:7999/lib/vhr-header-domain.git
git clone ssh://git@stash:7999/lib/vin-exchange-domain.git
git clone ssh://git@stash:7999/lib/vinalert-domain.git
git clone ssh://git@stash:7999/lib/vinhunter-domain.git
git clone ssh://git@stash:7999/lib/vinlogger-files.git
git clone ssh://git@stash:7999/lib/vinlogger-files-acceptance.git
git clone ssh://git@stash:7999/lib/vinThreaderDatabaseInterface.git
git clone ssh://git@stash:7999/lib/vzlite.git
git clone ssh://git@stash:7999/lib/vzlite-dsl.git
git clone ssh://git@stash:7999/lib/VzMetadata.git
git clone ssh://git@stash:7999/lib/web-encryption-extensions.git
git clone ssh://git@stash:7999/lib/webdriver-extensions.git
git clone ssh://git@stash:7999/lib/webdriver-fitnesse-extensions.git
git clone ssh://git@stash:7999/lib/weblogic-admin-extensions.git
git clone ssh://git@stash:7999/lib/xml-http-fixture.git
git clone ssh://git@stash:7999/lib/xml-service-domain.git
git clone ssh://git@stash:7999/lib/xml-testing.git
git clone ssh://git@stash:7999/lib/xml-utils.git